export default {
  'male-jackets': 'Мужская куртка',
  'male-costumes': 'Мужской костюм',
  'male-pants': 'Мужские брюки',
  'male-jeans': 'Мужские джинсы',
  'male-hoodies': 'Мужская худи',
  'male-longslivs': 'Мужской лонгслив',
  'male-suits': 'Мужской пиджак',
  'male-sweatshots': 'Мужской свитшот',
  'male-polos': 'Мужское поло',
  'male-shirts': 'Мужская рубашка',
  'male-t-shirts': 'Мужская футболка',
  'male-shorts': 'Мужские шорты',
  'male-underwear': 'Мужское нижнее белье',
  'male-socks': 'Мужские носки',
  'male-snickers': 'Мужские кроссовки',
  'male-lowshoes': 'Мужские туфли',
  'male-boots': 'Мужские ботинки',
  'male-chelsea': 'Мужские челси',
  'male-lofers': 'Мужские лоферы',
  'male-headdresses': 'Мужской головной убор',
  'male-glasses': 'Мужские очки',
  'male-backpacks': 'Мужской рюкзак',
  'male-bags': 'Мужская сумка',
  'female-jackets': 'Женская куртка',
  'female-pants': 'Женские брюки',
  'female-jeans': 'Женские джинсы',
  'female-hoodies': 'Женская худи',
  'female-longslivs': 'Женский лонгслив',
  'female-sweatshots': 'Женский свитшот',
  'female-dresses': 'Женское платье',
  'female-skirts': 'Женская юбка',
  'female-polos': 'Женское поло',
  'female-shirts': 'Женская рубашка',
  'female-t-shirts': 'Женская футболка',
  'female-shorts': 'Женские шорты',
  'female-underwear': 'Женское нижнее белье',
  'female-socks': 'Женские носки',
  'female-snickers': 'Женские кроссовки',
  'female-lowshoes': 'Женские туфли',
  'female-boots': 'Женские ботинки',
  'female-shelsea': 'Женские челси',
  'female-lofers': 'Женские лоферы',
  'female-headdresses': 'Женский головной убор',
  'female-glasses': 'Женские очки',
  'female-backpacks': 'Женский рюкзак',
  'female-bags': 'Женская сумка',
  'boys-jackets': 'Куртка для мальчиков',
  'boys-costumes': 'Костюм для мальчиков',
  'boys-pants': 'Брюки для мальчиков',
  'boys-jeans': 'Джинсы для мальчиков',
  'boys-hoodies': 'Худи для мальчиков',
  'boys-longslivs': 'Лонгслив для мальчиков',
  'boys-suits': 'Пиджак для мальчиков',
  'boys-sweatshots': 'Свитшот для мальчиков',
  'boys-polos': 'Поло для мальчиков',
  'boys-shirts': 'Рубашка для мальчиков',
  'boys-t-shirts': 'Футболка для мальчиков',
  'boys-shorts': 'Шорты для мальчиков',
  'boys-underwear': 'Нижнее белье для мальчиков',
  'boys-socks': 'Носки для мальчиков',
  'boys-snickers': 'Кроссовки для мальчиков',
  'boys-lowshoes': 'Туфли для мальчиков',
  'boys-boots': 'Ботинки для мальчиков',
  'boys-lofers': 'Лоферы для мальчиков',
  'boys-headdresses': 'Головной убор для мальчиков',
  'boys-glasses': 'Очки для мальчиков',
  'boys-backpacks': 'Рюкзак для мальчиков',
  'boys-bags': 'Сумка для мальчиков',
  'girls-jackets': 'Куртка для девочек',
  'girls-dresses': 'Платье для девочек',
  'girls-skirts': 'Юбка для девочек',
  'girls-pants': 'Брюки для девочек',
  'girls-jeans': 'Джинсы для девочек',
  'girls-hoodies': 'Худи для девочек',
  'girls-longslivs': 'Лонгслив для девочек',
  'girls-sweatshots': 'Свитшот для девочек',
  'girls-polos': 'Поло для девочек',
  'girls-shirts': 'Рубашка для девочек',
  'girls-t-shirts': 'Футболка для девочек',
  'girls-shorts': 'Шорты для девочек',
  'girls-underwear': 'Нижнее белье для девочек',
  'girls-socks': 'Носки для девочек',
  'girls-snickers': 'Кроссовки для девочек',
  'girls-lowshoes': 'Туфли для девочек',
  'girls-boots': 'Ботинки для девочек',
  'girls-lofers': 'Лоферы для девочек',
  'girls-headdresses': 'Головной убор для девочек',
  'girls-glasses': 'Очки для девочек',
  'girls-backpacks': 'Рюкзак для девочек',
  'girls-bags': 'Сумка для девочек'
}
