/* eslint-disable quote-props */
/* eslint-disable key-spacing */
export default {
  'male' : 'Мужчины',
  'female' : 'Женщины',
  'boys' : 'Мальчики',
  'girls' : 'Девочки',
  'kidsAll' : 'Дети',
  'adults': 'Взрослые',
  'sputnik' : 'CПУТНИК1985',
  'unost' : 'ЮНОСТЬ',
  'nike' : 'Nike',
  'reebok' : 'Reebok',
  'adidas' : 'Adidas',
  'jordan' : 'Jordan',
  'puma' : 'Puma',
  'vans' : 'Vans',
  'palace' : 'Palace',
  'supreme' : 'Supreme',
  'stoneisland' : 'Stone Island',
  'thenorthface' : 'The North Face',
  'gucci' : 'Gucci',
  'louisvuetton' : 'Louis Vuetton',
  'calvinklein' : 'Calvin Klein',
  'channel' : 'Channel',
  'ralphlauren' : 'Ralph Lauren',
  'wrangler' : 'Wrangler',
  'levis' : 'Levis',
  'drmartens' : 'Dr Martens',
  'assc' : 'ASSC',
  'batnorton' : 'Bat Norton',
  'shoes' : 'Обувь',
  'clothes' : 'Одежда',
  'accessoires' : 'Аксессуары',
  'jackets' : 'Куртки',
  'costumes' : 'Костюмы',
  'pants' : 'Брюки',
  'jeans' : 'Джинсы',
  'hoodies' : 'Худи',
  'longslivs' : 'Лонгсливы',
  'suits' : 'Пиджаки',
  'sweatshots' : 'Свитшоты',
  'polos' : 'Поло',
  'shirts' : 'Рубашки',
  't-shirts' : 'Футболки',
  'shorts' : 'Шорты',
  'underwear' : 'Нижнее белье',
  'socks' : 'Носки',
  'snickers' : 'Кроссовки',
  'lowshoes' : 'Туфли',
  'boots' : 'Ботинки',
  'chelsea': 'Челси',
  'lofers' : 'Лоферы',
  'headdresses' : 'Головные уборы',
  'glasses' : 'Очки',
  'backpacks' : 'Рюкзаки',
  'bags' : 'Сумки',
  'dresses' : 'Платья',
  'skirts' : 'Юбки',
  'newModelShoes' : 'Новая модель'
}
