/* eslint-disable quote-props */
/* eslint-disable key-spacing */
export default {
  'Мужчины' : 'male',
  'Женщины' : 'female',
  'Мальчики' : 'boys',
  'Девочки' : 'girls',
  'CПУТНИК1985' : 'sputnik',
  'ЮНОСТЬ' : 'unost',
  'Nike' : 'nike',
  'Reebok' : 'reebok',
  'Adidas' : 'adidas',
  'Jordan' : 'jordan',
  'Puma' : 'puma',
  'Vans' : 'vans',
  'Palace' : 'palace',
  'Supreme' : 'supreme',
  'Stone Island' : 'stoneisland',
  'The North Face' : 'thenorthface',
  'Gucci' : 'gucci',
  'Louis Vuetton' : 'louisvuetton',
  'Calvin Klein' : 'calvinklein',
  'Channel' : 'channel',
  'Ralph Lauren' : 'ralphlauren',
  'Wrangler' : 'wrangler',
  'Levis' : 'levis',
  'Dr Martens' : 'drmartens',
  'ASSC' : 'assc',
  'Bat Norton' : 'batnorton',
  'Обувь' : 'shoes',
  'Одежда' : 'clothes',
  'Аксессуары' : 'accessoires',
  'Куртки' : 'jackets',
  'Костюмы' : 'costumes',
  'Брюки' : 'pants',
  'Джинсы' : 'jeans',
  'Худи' : 'hoodies',
  'Лонгсливы' : 'longslivs',
  'Пиджаки' : 'suits',
  'Свитшоты' : 'sweatshots',
  'Поло' : 'polos',
  'Рубашки' : 'shirts',
  'Футболки' : 't-shirts',
  'Шорты' : 'shorts',
  'Нижнее белье' : 'underwear',
  'Носки' : 'socks',
  'Кроссовки' : 'snickers',
  'Туфли' : 'lowshoes',
  'Ботинки' : 'boots',
  'Челси': 'chelsea',
  'Лоферы' : 'lofers',
  'Головные уборы' : 'headdresses',
  'Очки' : 'glasses',
  'Рюкзаки' : 'backpacks',
  'Сумки' : 'bags',
  'Платья' : 'dresses',
  'Юбки' : 'skirts'
}
